name: Community Hero — Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-nestjs:
    name: Build NestJS Core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'backend-core/package-lock.json'

      - name: Install dependencies
        run: |
          cd backend-core
          npm ci

      - name: Build Application
        run: |
          cd backend-core
          npm run build

  build-react-dashboard:
    name: Build React Web Dashboard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'web-dashboard/package-lock.json'

      - name: Install dependencies
        run: |
          cd web-dashboard
          npm ci

      - name: Build Dashboard
        run: |
          cd web-dashboard
          npm run build
